import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define the base query function
const baseQuery = fetchBaseQuery({
  baseUrl: "https://hive.bcp.net.pk/api/v1",
});

// Create an API service using createApi
export const apiService = createApi({
  reducerPath: "HiveService",
  baseQuery,
  endpoints: (builder) => ({
    // New endpoint for making authenticated GET requests with token in payload
    fetchDataWithToken: builder.query({
      query: (endpoint, token) => ({
        url: `/${endpoint}`,
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
      }),
    }),
  }),
});

// Export hook generated by the service
export const { useFetchDataWithTokenQuery } = apiService;
