export const sidebarPathRoles = {
  ADMINISTRATOR: [
    "",
    "news_feed",
    "students",
    "my-services",
    "events_calender",
    "ptm-reports",
    "signin",
  ],
  ACE_COORDINATOR: [
    "",
    "news_feed",
    "ace-coordinator-activity",
    "ace-coordinator-achievements",
    "my-services",
    "ace-external-grading",
    "inbox",
    "signin",
  ],
  SCHOOL_HEAD: [
    "",
    "students",
    "news_feed",
    "ptm-reports",
    "events_calender",
    "my-services",
    "signin",
  ],
  CAREER_ADVISOR: ["", "news_feed", "all-university-applications", "signin"],
};
