export const active = [
  {
    id: 1,
    heading: "Test Competition",
    dates: "May 10th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Karachi",
    campus: "United States",
  },
  {
    id: 2,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Karachi",
    campus: "Canada",
  },
  {
    id: 3,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Islamabad",
    campus: "Germany",
  },
  {
    id: 4,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Multan",
    campus: "France",
  },
  {
    id: 5,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
    campus: "United States",
  },
  {
    id: 6,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Karachi",
  },
  {
    id: 7,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Islamabad",
  },
  {
    id: 8,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Karachi",
  },
  {
    id: 9,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
  },
  {
    id: 10,
    heading: "Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Lahore",
    campus: "France",
  },
  {
    id: 11,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 12,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
  },
  {
    id: 13,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 14,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
  },
  {
    id: 15,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Lahore",
  },
  {
    id: 16,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
  },
  {
    id: 17,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 18,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
  },
];

export const upcoming = [
  {
    id: 1,
    heading: "Cooking Competition",
    dates: "May 10th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 2,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 3,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 4,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 5,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 6,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 7,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
];
