export const active = [
  {
    id: 1,
    heading: "Test Competition",
    dates: "May 10th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Karachi",
    campus: "United States",
  },
  {
    id: 2,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Karachi",
    campus: "Canada",
  },
  {
    id: 3,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Islamabad",
    campus: "Germany",
  },
  {
    id: 4,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Multan",
    campus: "France",
  },
  {
    id: 5,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
    campus: "United States",
  },
  {
    id: 6,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Karachi",
  },
  {
    id: 7,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Islamabad",
  },
  {
    id: 8,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Karachi",
  },
  {
    id: 9,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
  },
  {
    id: 10,
    heading: "Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Lahore",
    campus: "France",
  },
  {
    id: 11,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 12,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
  },
  {
    id: 13,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 14,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
  },
  {
    id: 15,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "North",
    city: "Lahore",
  },
  {
    id: 16,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "South",
    city: "Lahore",
  },
  {
    id: 17,
    heading: "Food Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "East",
    city: "Lahore",
  },
  {
    id: 18,
    heading: "Sameer Festival",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
    region: "West",
    city: "Lahore",
    campus: "France",
  },
];

export const upcoming = [
  {
    id: 1,
    heading: "Cooking Competition",
    dates: "May 10th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 2,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 3,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 4,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 5,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 6,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
  {
    id: 7,
    heading: "Cultural diversity Knight",
    dates: "May 12th, 2023",
    attending: "60%",
    maybe: "30%",
    undecided: "10%",
  },
];

// news array
export const newsFeedData = [
  {
    count: 6,
    next: null,
    previous: null,
    results: [
      {
        id: 1,
        date_added: "2023-07-17T14:22:24.506427Z",
        date_last_modified: "2023-07-17T14:22:24.506427Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: null,
        type: "POST",
        owner: 1,
        attachments: [],
        likes: [],
        dislikes: [],
      },
      {
        id: 2,
        date_added: "2023-07-17T14:30:59.201751Z",
        date_last_modified: "2023-07-17T14:30:59.201751Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "quidem",
        type: "POST",
        owner: 1,
        attachments: ["73b23397b41689604059"],
        likes: [],
        dislikes: [],
      },
      {
        id: 3,
        date_added: "2023-07-17T14:40:34.756766Z",
        date_last_modified: "2023-07-17T14:40:34.757763Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "consequatur",
        type: "POST",
        owner: 1,
        attachments: ["73b23397b41689604059"],
        likes: [],
        dislikes: [],
      },
      {
        id: 4,
        date_added: "2024-05-27T15:41:38.408509Z",
        date_last_modified: "2023-07-17T14:41:38.408509Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "Molestias debitis recusandae accusamus ducimus non. Et unde soluta aut provident repellat quisquam natus dicta ea. Fuga cupiditate sunt optio. Ex iusto optio aut et quae quas. Aut nisi id rerum consequuntur quae sit quod.",
        type: "POST",
        owner: 1,
        attachments: ["73b23397b41689604059"],
        likes: [],
        dislikes: [],
      },
      {
        id: 5,
        date_added: "2023-07-17T14:42:01.031416Z",
        date_last_modified: "2023-07-17T14:42:01.031416Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "Recusandae voluptas dolorem nihil amet aut quis possimus. Consequatur consectetur in ea. Tenetur sint similique optio cupiditate et aspernatur laudantium at vero. Sint sint id itaque minima.",
        type: "POST",
        owner: 1,
        attachments: ["76f17e52bb1689604859"],
        likes: [],
        dislikes: [],
      },
      {
        id: 6,
        date_added: "2023-07-17T14:45:24.765911Z",
        date_last_modified: "2023-07-17T14:45:24.765911Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "Incidunt illo quia ad illum. Nesciunt ipsum rem et ut deleniti ut. Repellat sunt maxime dolor. Voluptates totam repudiandae.",
        type: "POST",
        owner: 1,
        attachments: ["76f17e52bb1689604859"],
        likes: [],
        dislikes: [],
      },

      {
        id: 7,
        date_added: "2023-07-17T14:45:24.765911Z",
        date_last_modified: "2023-07-17T14:45:24.765911Z",
        class_id: null,
        region_id: 2,
        city_id: null,
        branch_id: 225,
        text: "Incidunt illo quia ad illum. Nesciunt ipsum rem et ut deleniti ut. Repellat sunt maxime dolor. Voluptates totam repudiandae.",
        type: "POLL",
        owner: 1,
        attachments: ["76f17e52bb1689604859"],
        likes: [],
        dislikes: [],
      },
    ],
  },
];
